# Site settings
title: dotnetthoughts
header-img: img/home-bg.jpg
email: anuraj.p@dotnetthoughts.net
description: "dotnetthoughts.net - a dotnet developer's technical journal"
baseurl: ""
url: "http://dotnetthoughts.net"
twitter_username: anuraj
github_username:  anuraj
facebook_username:  dotnetthoughts

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]