# Site settings
title: 'dotnet thoughts' # Your Title
tagline: 'a dotnet developer&#39;s technical journal' # A brief tagline for your site
sidebar_image: /images/cover.jpg
permalink: /:title
# Build settings
markdown: redcarpet
highlighter: pygments
baseurl:  # the subpath of your site, e.g. /blog/
