# Site settings
host : dotnetthoughts.net
name : dotnetthoughts
description: a dotnet developer's technical journal
author : "Anuraj P"
author_bio : "Anuraj Parameswaran works as an architect in Orion India Systems Pvt. Ltd, Kochi. He has been working on .NET platform since its early days. He is a co-founder of mobithoughts, a mobile application development company. His focus areas are Data Analytics, Architecture and Cloud computing." 
baseurl : ""
twitter_username: anuraj
github_username:  anuraj
facebook_username: dotnetthoughts
googleplus_username : 105671778313820571858
disqus_shortname: dotnetthoughts
google_analytics: 'UA-12179122-1'
gravatar_hash : ab9111466be86e8e027c658e8dc1778f
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:title/
paginate: 7
showFeed : true
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
  - jekyll-sitemap
  - jekyll-feed
compress_html:
  clippings: all
  comments: all
  endings: all
