# Site settings
title: dotnetthoughts
header-img: img/home-bg.jpg
description: "dotnetthoughts.net - a dotnet developer's technical journal"
baseurl: ""
url: "http://dotnetthoughts.net"
twitter_username: anuraj
github_username:  anuraj
facebook_username: dotnetthoughts
googleplus_username : 105671778313820571858
disqus_shortname: dotnetthoughts
google_analytics: 'UA-12179122-1'
# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  endings: all